<?php namespace Pta\Formbuilder\Lib\Fields;


class CountrySelectField implements FieldInterface {

    protected $values;

    public function __construct()
    {
        $this->values = array(
            (object) array('id'=>"AF",'name' => "Afghanistan"),
            (object) array('id'=>"AL" ,'name'=> "Albania"),
            (object) array('id'=>"DZ" ,'name'=> "Algeria"),
            (object) array('id'=>"AS" ,'name'=> "American Samoa"),
            (object) array( 'id'=>"AD" ,'name'=> "Andorra"),
            (object) array('id'=>"AO" ,'name'=> "Angola"),
            (object) array('id'=>"AI" ,'name'=> "Anguilla"),
            (object) array('id'=>"AQ" ,'name'=> "Antarctica"),
            (object) array('id'=>"AG" ,'name'=> "Antigua and Barbuda"),
            (object) array('id'=>"AR" ,'name'=> "Argentina"),
            (object) array('id'=>"AM" ,'name'=> "Armenia"),
            (object) array('id'=>"AW" ,'name'=> "Aruba"),
            (object) array('id'=>"AU" ,'name'=> "Australia"),
            (object) array('id'=>"AT" ,'name'=> "Austria"),
            (object) array('id'=>"AZ" ,'name'=> "Azerbaijan"),
            (object) array('id'=>"BS" ,'name'=> "Bahamas"),
            (object) array('id'=>"BH" ,'name'=> "Bahrain"),
            (object) array('id'=>"BD" ,'name'=> "Bangladesh"),
            (object) array('id'=>"BB" ,'name'=> "Barbados"),
            (object) array('id'=>"BY" ,'name'=> "Belarus"),
            (object) array('id'=>"BE" ,'name'=> "Belgium"),
            (object) array('id'=>"BZ" ,'name'=> "Belize"),
            (object) array('id'=>"BJ" ,'name'=> "Benin"),
            (object) array('id'=>"BM" ,'name'=> "Bermuda"),
            (object) array('id'=>"BT" ,'name'=> "Bhutan"),
            (object) array('id'=>"BO" ,'name'=> "Bolivia"),
            (object) array('id'=>"BA" ,'name'=> "Bosnia and Herzegovina"),
            (object) array('id'=>"BW" ,'name'=> "Botswana"),
            (object) array('id'=>"BV" ,'name'=> "Bouvet Island"),
            (object) array('id'=>"BR" ,'name'=> "Brazil"),
            (object) array('id'=>"BQ" ,'name'=> "British Antarctic Territory"),
            (object) array('id'=>"IO" ,'name'=> "British Indian Ocean Territory"),
            (object) array('id'=>"VG" ,'name'=> "British Virgin Islands"),
            (object) array('id'=>"BN" ,'name'=> "Brunei"),
            (object) array('id'=>"BG" ,'name'=> "Bulgaria"),
            (object) array('id'=>"BF" ,'name'=> "Burkina Faso"),
            (object) array('id'=>"BI" ,'name'=> "Burundi"),
            (object) array('id'=>"KH" ,'name'=> "Cambodia"),
            (object) array('id'=>"CM" ,'name'=> "Cameroon"),
            (object) array('id'=>"CA" ,'name'=> "Canada"),
            (object) array('id'=>"CT" ,'name'=> "Canton and Enderbury Islands"),
            (object) array('id'=>"CV" ,'name'=> "Cape Verde"),
            (object) array('id'=>"KY" ,'name'=> "Cayman Islands"),
            (object) array('id'=>"CF" ,'name'=> "Central African Republic"),
            (object) array('id'=>"TD" ,'name'=> "Chad"),
            (object) array('id'=>"CL" ,'name'=> "Chile"),
            (object) array('id'=>"CN" ,'name'=> "China"),
            (object) array('id'=>"CX" ,'name'=> "Christmas Island"),
            (object) array('id'=>"CC" ,'name'=> "Cocos [Keeling] Islands"),
            (object) array('id'=>"CO" ,'name'=> "Colombia"),
            (object) array('id'=>"KM" ,'name'=> "Comoros"),
            (object) array('id'=>"CG" ,'name'=> "Congo - Brazzaville"),
            (object) array('id'=>"CD" ,'name'=> "Congo - Kinshasa"),
            (object) array('id'=>"CK" ,'name'=> "Cook Islands"),
            (object) array('id'=>"CR" ,'name'=> "Costa Rica"),
            (object) array('id'=>"HR" ,'name'=> "Croatia"),
            (object) array('id'=>"CU" ,'name'=> "Cuba"),
            (object) array('id'=>"CY" ,'name'=> "Cyprus"),
            (object) array('id'=>"CZ" ,'name'=> "Czech Republic"),
            (object) array('id'=>"CI" ,'name'=> "Côte d’Ivoire"),
            (object) array('id'=>"DK" ,'name'=> "Denmark"),
            (object) array('id'=>"DJ" ,'name'=> "Djibouti"),
            (object) array('id'=>"DM" ,'name'=> "Dominica"),
            (object) array('id'=>"DO" ,'name'=> "Dominican Republic"),
            (object) array('id'=>"NQ" ,'name'=> "Dronning Maud Land"),
            (object) array('id'=>"DD" ,'name'=> "East Germany"),
            (object) array('id'=>"EC" ,'name'=> "Ecuador"),
            (object) array('id'=>"EG" ,'name'=> "Egypt"),
            (object) array('id'=>"SV" ,'name'=> "El Salvador"),
            (object) array('id'=>"GQ" ,'name'=> "Equatorial Guinea"),
            (object) array('id'=>"ER" ,'name'=> "Eritrea"),
            (object) array('id'=>"EE" ,'name'=> "Estonia"),
            (object) array('id'=>"ET" ,'name'=> "Ethiopia"),
            (object) array('id'=>"FK" ,'name'=> "Falkland Islands"),
            (object) array('id'=>"FO" ,'name'=> "Faroe Islands"),
            (object) array('id'=>"FJ" ,'name'=> "Fiji"),
            (object) array('id'=>"FI" ,'name'=> "Finland"),
            (object) array('id'=>"FR" ,'name'=> "France"),
            (object) array('id'=>"GF" ,'name'=> "French Guiana"),
            (object) array('id'=>"PF" ,'name'=> "French Polynesia"),
            (object) array('id'=>"TF" ,'name'=> "French Southern Territories"),
            (object) array('id'=>"FQ" ,'name'=> "French Southern and Antarctic Territories"),
            (object) array('id'=>"GA" ,'name'=> "Gabon"),
            (object) array('id'=>"GM" ,'name'=> "Gambia"),
            (object) array('id'=>"GE" ,'name'=> "Georgia"),
            (object) array('id'=>"DE" ,'name'=> "Germany"),
            (object) array('id'=>"GH" ,'name'=> "Ghana"),
            (object) array('id'=>"GI" ,'name'=> "Gibraltar"),
            (object) array('id'=>"GR" ,'name'=> "Greece"),
            (object) array('id'=>"GL" ,'name'=> "Greenland"),
            (object) array('id'=>"GD" ,'name'=> "Grenada"),
            (object) array('id'=>"GP" ,'name'=> "Guadeloupe"),
            (object) array('id'=>"GU" ,'name'=> "Guam"),
            (object) array('id'=>"GT" ,'name'=> "Guatemala"),
            (object) array('id'=>"GG" ,'name'=> "Guernsey"),
            (object) array('id'=>"GN" ,'name'=> "Guinea"),
            (object) array('id'=>"GW" ,'name'=> "Guinea-Bissau"),
            (object) array('id'=>"GY" ,'name'=> "Guyana"),
            (object) array('id'=>"HT" ,'name'=> "Haiti"),
            (object) array('id'=>"HM" ,'name'=> "Heard Island and McDonald Islands"),
            (object) array('id'=>"HN" ,'name'=> "Honduras"),
            (object) array('id'=>"HK" ,'name'=> "Hong Kong SAR China"),
            (object) array('id'=>"HU" ,'name'=> "Hungary"),
            (object) array('id'=>"IS" ,'name'=> "Iceland"),
            (object) array('id'=>"IN" ,'name'=> "India"),
            (object) array('id'=>"ID" ,'name'=> "Indonesia"),
            (object) array('id'=>"IR" ,'name'=> "Iran"),
            (object) array('id'=>"IQ" ,'name'=> "Iraq"),
            (object) array('id'=>"IE" ,'name'=> "Ireland"),
            (object) array('id'=>"IM" ,'name'=> "Isle of Man"),
            (object) array('id'=>"IL" ,'name'=> "Israel"),
            (object) array('id'=>"IT" ,'name'=> "Italy"),
            (object) array('id'=>"JM" ,'name'=> "Jamaica"),
            (object) array('id'=>"JP" ,'name'=> "Japan"),
            (object) array('id'=>"JE" ,'name'=> "Jersey"),
            (object) array('id'=>"JT" ,'name'=> "Johnston Island"),
            (object) array('id'=>"JO" ,'name'=> "Jordan"),
            (object) array('id'=>"KZ" ,'name'=> "Kazakhstan"),
            (object) array('id'=>"KE" ,'name'=> "Kenya"),
            (object) array('id'=>"KI" ,'name'=> "Kiribati"),
            (object) array('id'=>"KW" ,'name'=> "Kuwait"),
            (object) array('id'=>"KG" ,'name'=> "Kyrgyzstan"),
            (object) array('id'=>"LA" ,'name'=> "Laos"),
            (object) array('id'=>"LV" ,'name'=> "Latvia"),
            (object) array('id'=>"LB" ,'name'=> "Lebanon"),
            (object) array('id'=>"LS" ,'name'=> "Lesotho"),
            (object) array('id'=>"LR" ,'name'=> "Liberia"),
            (object) array('id'=>"LY" ,'name'=> "Libya"),
            (object) array('id'=>"LI" ,'name'=> "Liechtenstein"),
            (object) array('id'=>"LT" ,'name'=> "Lithuania"),
            (object) array('id'=>"LU" ,'name'=> "Luxembourg"),
            (object) array('id'=>"MO" ,'name'=> "Macau SAR China"),
            (object) array('id'=>"MK" ,'name'=> "Macedonia"),
            (object) array('id'=>"MG" ,'name'=> "Madagascar"),
            (object) array('id'=>"MW" ,'name'=> "Malawi"),
            (object) array('id'=>"MY" ,'name'=> "Malaysia"),
            (object) array('id'=>"MV" ,'name'=> "Maldives"),
            (object) array('id'=>"ML" ,'name'=> "Mali"),
            (object) array('id'=>"MT" ,'name'=> "Malta"),
            (object) array('id'=>"MH" ,'name'=> "Marshall Islands"),
            (object) array('id'=>"MQ" ,'name'=> "Martinique"),
            (object) array('id'=>"MR" ,'name'=> "Mauritania"),
            (object) array('id'=>"MU" ,'name'=> "Mauritius"),
            (object) array('id'=>"YT" ,'name'=> "Mayotte"),
            (object) array('id'=>"FX" ,'name'=> "Metropolitan France"),
            (object) array('id'=>"MX" ,'name'=> "Mexico"),
            (object) array('id'=>"FM" ,'name'=> "Micronesia"),
            (object) array('id'=>"MI" ,'name'=> "Midway Islands"),
            (object) array('id'=>"MD" ,'name'=> "Moldova"),
            (object) array('id'=>"MC" ,'name'=> "Monaco"),
            (object) array('id'=>"MN" ,'name'=> "Mongolia"),
            (object) array('id'=>"ME" ,'name'=> "Montenegro"),
            (object) array('id'=>"MS" ,'name'=> "Montserrat"),
            (object) array('id'=>"MA" ,'name'=> "Morocco"),
            (object) array('id'=>"MZ" ,'name'=> "Mozambique"),
            (object) array('id'=>"MM" ,'name'=> "Myanmar [Burma]"),
            (object) array('id'=>"NA" ,'name'=> "Namibia"),
            (object) array('id'=>"NR" ,'name'=> "Nauru"),
            (object) array('id'=>"NP" ,'name'=> "Nepal"),
            (object) array('id'=>"NL" ,'name'=> "Netherlands"),
            (object) array('id'=>"AN" ,'name'=> "Netherlands Antilles"),
            (object) array('id'=>"NT" ,'name'=> "Neutral Zone"),
            (object) array('id'=>"NC" ,'name'=> "New Caledonia"),
            (object) array('id'=>"NZ" ,'name'=> "New Zealand"),
            (object) array('id'=>"NI" ,'name'=> "Nicaragua"),
            (object) array('id'=>"NE" ,'name'=> "Niger"),
            (object) array('id'=>"NG" ,'name'=> "Nigeria"),
            (object) array('id'=>"NU" ,'name'=> "Niue"),
            (object) array('id'=>"NF" ,'name'=> "Norfolk Island"),
            (object) array('id'=>"KP" ,'name'=> "North Korea"),
            (object) array('id'=>"VD" ,'name'=> "North Vietnam"),
            (object) array('id'=>"MP" ,'name'=> "Northern Mariana Islands"),
            (object) array('id'=>"NO" ,'name'=> "Norway"),
            (object) array('id'=>"OM" ,'name'=> "Oman"),
            (object) array('id'=>"PC" ,'name'=> "Pacific Islands Trust Territory"),
            (object) array('id'=>"PK" ,'name'=> "Pakistan"),
            (object) array('id'=>"PW" ,'name'=> "Palau"),
            (object) array('id'=>"PS" ,'name'=> "Palestinian Territories"),
            (object) array('id'=>"PA" ,'name'=> "Panama"),
            (object) array('id'=>"PZ" ,'name'=> "Panama Canal Zone"),
            (object) array('id'=>"PG" ,'name'=> "Papua New Guinea"),
            (object) array('id'=>"PY" ,'name'=> "Paraguay"),
            (object) array('id'=>"YD" ,'name'=> "People's Democratic Republic of Yemen"),
            (object) array('id'=>"PE" ,'name'=> "Peru"),
            (object) array('id'=>"PH" ,'name'=> "Philippines"),
            (object) array('id'=>"PN" ,'name'=> "Pitcairn Islands"),
            (object) array('id'=>"PL" ,'name'=> "Poland"),
            (object) array('id'=>"PT" ,'name'=> "Portugal"),
            (object) array('id'=>"PR" ,'name'=> "Puerto Rico"),
            (object) array('id'=>"QA" ,'name'=> "Qatar"),
            (object) array('id'=>"RO" ,'name'=> "Romania"),
            (object) array('id'=>"RU" ,'name'=> "Russia"),
            (object) array('id'=>"RW" ,'name'=> "Rwanda"),
            (object) array('id'=>"RE" ,'name'=> "Réunion"),
            (object) array('id'=>"BL" ,'name'=> "Saint Barthélemy"),
            (object) array('id'=>"SH" ,'name'=> "Saint Helena"),
            (object) array('id'=>"KN" ,'name'=> "Saint Kitts and Nevis"),
            (object) array('id'=>"LC" ,'name'=> "Saint Lucia"),
            (object) array('id'=>"MF" ,'name'=> "Saint Martin"),
            (object) array('id'=>"PM" ,'name'=> "Saint Pierre and Miquelon"),
            (object) array('id'=>"VC" ,'name'=> "Saint Vincent and the Grenadines"),
            (object) array('id'=>"WS" ,'name'=> "Samoa"),
            (object) array('id'=>"SM" ,'name'=> "San Marino"),
            (object) array('id'=>"SA" ,'name'=> "Saudi Arabia"),
            (object) array('id'=>"SN" ,'name'=> "Senegal"),
            (object) array('id'=>"RS" ,'name'=> "Serbia"),
            (object) array('id'=>"CS" ,'name'=> "Serbia and Montenegro"),
            (object) array('id'=>"SC" ,'name'=> "Seychelles"),
            (object) array('id'=>"SL" ,'name'=> "Sierra Leone"),
            (object) array('id'=>"SG" ,'name'=> "Singapore"),
            (object) array('id'=>"SK" ,'name'=> "Slovakia"),
            (object) array('id'=>"SI" ,'name'=> "Slovenia"),
            (object) array('id'=>"SB" ,'name'=> "Solomon Islands"),
            (object) array('id'=>"SO" ,'name'=> "Somalia"),
            (object) array('id'=>"ZA" ,'name'=> "South Africa"),
            (object) array('id'=>"GS" ,'name'=> "South Georgia and the South Sandwich Islands"),
            (object) array('id'=>"KR" ,'name'=> "South Korea"),
            (object) array('id'=>"ES" ,'name'=> "Spain"),
            (object) array('id'=>"LK" ,'name'=> "Sri Lanka"),
            (object) array('id'=>"SD" ,'name'=> "Sudan"),
            (object) array('id'=>"SR" ,'name'=> "Suriname"),
            (object) array('id'=>"SJ" ,'name'=> "Svalbard and Jan Mayen"),
            (object) array('id'=>"SZ" ,'name'=> "Swaziland"),
            (object) array('id'=>"SE" ,'name'=> "Sweden"),
            (object) array('id'=>"CH" ,'name'=> "Switzerland"),
            (object) array('id'=>"SY" ,'name'=> "Syria"),
            (object) array('id'=>"ST" ,'name'=> "São Tomé and Príncipe"),
            (object) array('id'=>"TW" ,'name'=> "Taiwan"),
            (object) array('id'=>"TJ" ,'name'=> "Tajikistan"),
            (object) array('id'=>"TZ" ,'name'=> "Tanzania"),
            (object) array('id'=>"TH" ,'name'=> "Thailand"),
            (object) array('id'=>"TL" ,'name'=> "Timor-Leste"),
            (object) array('id'=>"TG" ,'name'=> "Togo"),
            (object) array('id'=>"TK" ,'name'=> "Tokelau"),
            (object) array('id'=>"TO" ,'name'=> "Tonga"),
            (object) array('id'=>"TT" ,'name'=> "Trinidad and Tobago"),
            (object) array('id'=>"TN" ,'name'=> "Tunisia"),
            (object) array('id'=>"TR" ,'name'=> "Turkey"),
            (object) array('id'=>"TM" ,'name'=> "Turkmenistan"),
            (object) array('id'=>"TC" ,'name'=> "Turks and Caicos Islands"),
            (object) array('id'=>"TV" ,'name'=> "Tuvalu"),
            (object) array('id'=>"UM" ,'name'=> "U.S. Minor Outlying Islands"),
            (object) array('id'=>"PU" ,'name'=> "U.S. Miscellaneous Pacific Islands"),
            (object) array('id'=>"VI" ,'name'=> "U.S. Virgin Islands"),
            (object) array('id'=>"UG" ,'name'=> "Uganda"),
            (object) array('id'=>"UA" ,'name'=> "Ukraine"),
            (object) array('id'=>"SU" ,'name'=> "Union of Soviet Socialist Republics"),
            (object) array('id'=>"AE" ,'name'=> "United Arab Emirates"),
            (object) array('id'=>"GB" ,'name'=> "United Kingdom"),
            (object) array('id'=>"US" ,'name'=> "United States"),
            (object) array('id'=>"ZZ" ,'name'=> "Unknown or Invalid Region"),
            (object) array('id'=>"UY" ,'name'=> "Uruguay"),
            (object) array('id'=>"UZ" ,'name'=> "Uzbekistan"),
            (object) array('id'=>"VU" ,'name'=> "Vanuatu"),
            (object) array('id'=>"VA" ,'name'=> "Vatican City"),
            (object) array('id'=>"VE" ,'name'=> "Venezuela"),
            (object) array('id'=>"VN" ,'name'=> "Vietnam"),
            (object) array('id'=>"WK" ,'name'=> "Wake Island"),
            (object) array('id'=>"WF" ,'name'=> "Wallis and Futuna"),
            (object) array('id'=>"EH" ,'name'=> "Western Sahara"),
            (object) array('id'=>"YE" ,'name'=> "Yemen"),
            (object) array('id'=>"ZM" ,'name'=> "Zambia"),
            (object) array('id'=>"ZW" ,'name'=> "Zimbabwe"),
            (object) array('id'=>"AX" ,'name'=> "Åland Islands"),
        );
    }


    /**
     * This uses the data from getData to properly format a Select Form Field
     * @param $field
     * @param $labels
     * @param $fieldData
     * @param $required
     * @param $trans
     * @return Illuminate\View\View
     */
    public function getFormat($field, $labels, $fieldData = null, $required = false, $trans = null)
    {
        $data = $this->values;
        if(!is_null($fieldData)){
            return view('pta/formbuilder::partials/fields/select')->with('data',$data)->with('field',$field->Field)->with('labels', $labels)->with('fieldData',$fieldData)->with('required',$required)->with('trans', $trans)->render();
        }
        return view('pta/formbuilder::partials/fields/select')->with('data',$data)->with('field',$field->Field)->with('labels', $labels)->with('required',$required)->with('trans', $trans)->render();

    }

}